### ISSUE TITLE
CyberGlow Rework for v8

### ISSUE THREAD

**Issue by ArtexJay** [ArtexJay/Obsidian-CyberGlow#42]
Will be going through the current code, slowly rebuilding it and finding the redundant or unnecessary code or combine code that are able to. 
Arrange the code once and for all and hopefully reduce theme size.
Will add comments in code portion to describe what it does.
Will address the following issues
- [x] Total Rework of the CSS code
- [x] Window popout Styling #41 / #49 
- [x] Mobile Search function is hidden following new update #53 
- [x] Incorrect Heading Sizes  #52 
- [x] https://github.com/ArtexJay/Obsidian-CyberGlow/issues/55

Edit:

The massive amounts of revision and changes for the upcoming version 8 of CyberGlow. 
If this theme was a TV show you'd say this is an enhanced Remaster.

Changes this week :
- Implemented Light Mode 
- Desktop Version has been finalized
- Revised the entirety of Sidepanels on Mobile
- Fixed hidden search box due to new Search Interface from Obsidian update
- Revised the Note view style on Mobile
- Fixed bad theme's Kanban view implementation on Mobile
- Rewrote the code for search finder/replace on mobile, it will properly bump down the note for full visibility.
- Revised entirety of Settings page on phone
- Revised theme for Tablet
- NEW Added Style Settings option to disable the Header Indications like H1, H2, etc

Current Changelog, more changes are coming
 - Complete code rework of CyberGlow theme with the following changes:
 - Totally Streamlined code 
 - Rewrote Tab Styling
 - Rewrote Window Control Buttons Styling
 - Rewrote custom Scrollbar Implementation
 - NEW Added Line Hover and Focus
 - Styling updated for new Search
 - Rewrote Prompt Styling
 - Removed Certain Style Settings Options
 - Rewrote Menu Styling
 - Enhanced visibility for the Glow Effect on Heading
 - Corrected wrong Size for Heading 4
 - Heading 1 Glow will follow chosen Accent
 - Rewrote Settings Modal Style
 - Rewrote Settings Community Modals Style
 - NEW design for Buttons/Dropdowns 
 - Resolved Issue where nav items/parent were being dislocated
 - Rewrote Progress Bar Styling
 - Rewrote Surfing Plugin Style
 - Rewrote LanguageTool Integration Plugin Style
 - Rewrote Style Settings Page Style
 - Replaced Obsidianite Style Bold/Italics with one closer to CyberGlow's Style
  - This should resolve invisible text issue on Linux
 - NEW Added Strikeout Text Style
 - NEW Added Underline Text Style
 - Rewrote Blockquotes Styling
 - Rewrote Codeblock Styling
 - Rewrote Empty State Document Styling
 - Rewrote Canvas Style
 - NEW Added Style for Canvas Labels
 - Rewrote Kanban Styling
 - NEW Added Styling for Updated Default PDF 2.0 Viewer
 - Rewrote Textbox Style
 - Streamlined Lists Bullets
 - Revised Links Styling 
 - Re-implemented Cyber Glow's Style Settings
 - Added New Obsidian Icon for SidePanel Option, removed Custom DrIcon's option.
 - Removed Transparent Headers on Desktop, created too many issues in both desktop, phone and tablet. And was difficult to correct as well as bloated the theme.
 - Reviewed Implementation of Style Settings Background Image
- Better Background Image Transparency in Obsidian Frame
- Rewrote Breadcrumbs Styling in Header
- NEW In Obsidian Frame custom (Sidepanel) Icon now available.
- Changed the dead link for Hyrule svg

**Comment by ArtexJay** [comment]
Reworking of the theme will start next week. There is no eta as of yet

**Comment by ArtexJay** [comment]
#41 / #49  issue has been resolved ".ͼ1" broke the popout window stylings

**Comment by ArtexJay** [comment]
Not a bug, https://github.com/ArtexJay/Obsidian-CyberGlow/issues/47 Icon is now properly styled in-line with the Theme with style settings.

**Comment by ArtexJay** [comment]
Desktop version is being finalized. Work on the phone/tablet version of the theme will begin very soon. I'm predicting they won't take as long as the desktop version.

**Comment by ArtexJay** [comment]
Current projected ETA is to complete the entirety rework by the end of this month.

**Comment by ArtexJay** [comment]
Desktop Theme has been finalized, will begin looking at the mobile variant shortly.

**Comment by ArtexJay** [comment]
The Rewrite Update is nearing completion, is currently ahead of the set due date. Release is imminent.
